New Item: Irresistable Star
ark120202/aabs pull request #224
Opened 2018-07-01 18:29 UTC by shimaosu

2018-07-01 22:22 UTC, ark120202 requested changes

2018-07-01 22:22 UTC, ark120202 commented on localization/english/items.yml
> +  <h1>Пассивная: Shine</h1> All your abilities deal %magic_damage_to_pure_pct%%% pure damage.
Use the same description as Scythe of the Ancients uses

2018-07-01 22:22 UTC, ark120202 commented on game/scripts/npc/npc_items_custom.txt
> +				"bonus_intellect"	"45"
Passive bonuses should go first

2018-07-01 22:22 UTC, ark120202 commented on game/scripts/npc/npc_items_custom.txt
> +				"bonus_intellect"	"45"
Special values should be aligned

2018-08-09 10:09 UTC, shimaosu commented
Will be reworked without quasar changes soon.

2018-09-25 07:51 UTC, shimaosu commented
Revert hero selection changes

2019-04-03 03:25 UTC, closed without merging